spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mpw:okPilpUF0EXmfWE649Leyyn9JyuEehOXmbPJ1gmXgxaUEMXVeLl+Hdni0M/+jInR15fw9nYNdMEoaMEEalgN/Dpicsrnv464WmpWPFL8a0sV9RHN3hPhapLEtwiBZVxgpJBLLpzMebL59jC5X75td1KFpH8I14xq6NLQ+YXyCt+uGFc/SkJfnskgG9Xh/Z/0REyxDbiMUnk/JzNVWhh8q/jSydYxHx56OZxcmbCI4UrURa6JJAMhJMkPYp2H//Fg
    username: mpw:UHFlRzvX3UX7TTAIDw6zDg==
    password: mpw:9IkA0v5o/lF3rJD8H5taHw==

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.yzm.plus03.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true